# Copyright (c) 2024 Lemur-Catta.org
# Author: Sylvain Gubian <sgubian@lemur-catta.org>

services:
  picasort-db:
    image: picasortdb:latest
    container_name: picasort-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/postgresql
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    secrets:
      - db_password
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  db_data:
secrets:
  db_password:
    file: ./secrets/db_password.txt
